apiVersion: v1
kind: Service
metadata:
  name: my-service-test
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    targetPort: 81
    protocol: TCP
    nodePort: 30001
  type: NodePort