apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: cm9vdA==
  password: cHc=
  key_id: QVNJQVlSUFVMRzdJMjJPRVIzVUY=
  access_key: TTEzR0ROMHZvL0F2YnRwOEJqMHEvcklQZE56VFRHNit2blBUQ3RGMw==
  session_token: RndvR1pYSXZZWGR6RUUwYUREVE84NDN2aFIzZVlYN2s4Q0xKQVozWFd4R0VLbHVmd25aWkRoby9GZ2p0ZWpSSXdudHFkdkRqd0pxMmF2cFV4VU1rV1JJbFpJajkrMW4rKzgyejBuNVYydmxFOXRjblh3K2o1WVZOaVpKbnhBK3JxY2VQdFAyalQ4YVM0VngrVXNBbFdYSmxYR2ZyUENTeThwN0RraHZXalpVUlg2YVNIV0I3eGtMdlpxL0J1c1pscFZDa1Qrb3BnN0VyZUhuRTJ0eStUdUdmV1VsaWwzTXN6Z2NmRjM3dWc3SFNrbmx3Nk0rbE9oWkQ0d3BWazU2SmVwOEFuK1VWWVdndjN5NVdCU0ZxMjdkZ1c4bDNjMFNaWDEydXJJcWpSdEFydTQ4SXdpaWpwL0doQmpJdGNJOXFCWGExT21xeWo4TU1yemdweTdWenE0UjZmTU8vcCsvYXVFbEY0OEwxM0RXOWR6ejNURWw0N090Rw==