
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: sqldb
        image: 587312347089.dkr.ecr.us-east-1.amazonaws.com/mysql:v1.34
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: web-data
            mountPath: /var/lib/mysql
      volumes:
        - name: web-data
          persistentVolumeClaim:
            claimName: web-data
      imagePullSecrets:
      - name: regcred